---
apiVersion: v1
kind: ConfigMap
metadata:
 name: oauth-config
data:
  oauth2-proxy.cfg: |+
    http_address="0.0.0.0:4180"
    cookie_secret="${cookieSecret}"
    cookie_secure="false"
    email_domains='*'

    pass_authorization_header='true'
    pass_access_token='true'
  
    set_authorization_header = true
    ssl_insecure_skip_verify = true
    ssl_upstream_insecure_skip_verify = true
    
    # the http url(s) of the upstream endpoint. If multiple, routing is based on path
    upstreams = "http://127.0.0.1:8080/"

    cookie_domains=[".${appsUrl}"] # Required so cookie can be read on all subdomains.
    whitelist_domains=[".${appsUrl}"] # Required to allow redirection back to original requested target.

    # keycloak provider
    provider="keycloak-oidc"
    provider_display_name="Keycloak"

    client_secret="${clientSecret}"
    client_id="oauth2-proxy"

    oidc_issuer_url="https://sso-${PROJECT}.${appsUrl}/realms/master"
    
    redirect_url="https://flask-${PROJECT}.${appsUrl}/oauth2/callback"
