---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
 name: flask
 labels:
   app: flask
spec:
 strategy:
   type: Rolling
 replicas: 1
 selector:
   app: flask
 template:
   metadata:
     labels:
       app: flask
   spec:
     containers:
       - name: flask
         image: quay.io/snowjet/flask-sso-gatekeeper@sha256:44b52c5ed977710bb33e4c56b90dec85f0814b613581a3cad9b69bd1fe2766a0
         ports:
           - containerPort: 8080
             protocol: TCP
         envFrom:
           - configMapRef:
               name: sso-public-key
         imagePullPolicy: IfNotPresent
       - name: oauth2
         image: ${oauth2ContainerUrl}
         args:
           - --config=/etc/oauth2-proxy.cfg
         ports:
           - containerPort: 4180
             name: oauth2
         volumeMounts:
           - name: oauth-config
             mountPath: /etc/oauth2-proxy.cfg
             subPath: oauth2-proxy.cfg
     volumes:
       - name : oauth-config
         configMap:
           name: oauth-config
